# This workflow will run tests using node and then publish a package to GitHub Packages when a release is created
# For more information see: https://docs.github.com/en/actions/publishing-packages/publishing-nodejs-packages

name: Node.js Package

on:
  push:
    branches:
      - master
    paths: "package.json"

jobs:
  publish-npm:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: "20.x"
          registry-url: https://registry.npmjs.org/
      - name: Install jq
        run: sudo apt-get install jq
      - name: Check if version changed
        id: version_changed
        run: |
          VERSION_OLD=$(git show ${{ github.event.before }}:package.json | jq -r .version)
          VERSION_NEW=$(jq -r .version package.json)
          if [ "$VERSION_OLD" != "$VERSION_NEW" ]; then
            echo "Version changed from $VERSION_OLD to $VERSION_NEW"
            echo "changed=true" >> $GITHUB_OUTPUT
          else
            echo "Version did not change"
            echo "changed=false" >> $GITHUB_OUTPUT
          fi
      - name: Publish to npm
        if: steps.version_changed.outputs.changed == 'true'
        run: |
          npm ci --force
          npm run build
          npm publish --access public
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_PUBLISH_TOKEN}}
